<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0220ENSkillsNetwork900-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

<h1>Extracting and Visualizing Stock Data</h1>
<h2>Description</h2>

Extracting essential data from a dataset and displaying it is a necessary part of data science; therefore individuals can make correct decisions based on the data. In this assignment, you will extract some stock data, you will then display this data in a graph.

<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li>Define a Function that Makes a Graph</li>
        <li>Question 1: Use yfinance to Extract Stock Data</li>
        <li>Question 2: Use Webscraping to Extract Tesla Revenue Data</li>
        <li>Question 3: Use yfinance to Extract Stock Data</li>
        <li>Question 4: Use Webscraping to Extract GME Revenue Data</li>
        <li>Question 5: Plot Tesla Stock Graph</li>
        <li>Question 6: Plot GameStop Stock Graph</li>
    </ul>
<p>
    Estimated Time Needed: <strong>30 min</strong></p>
</div>

<hr>

***Note***:- If you are working in IBM Cloud Watson Studio, please replace the command for installing nbformat from `!pip install nbformat==4.2.0` to simply `!pip install nbformat`

In [1]:
!pip install yfinance==0.1.67
!mamba install bs4==4.10.0 -y
!pip install nbformat==4.2.0

Collecting yfinance==0.1.67
  Downloading yfinance-0.1.67-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: pandas>=0.24 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (1.3.5)
Requirement already satisfied: numpy>=1.15 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (1.21.6)
Requirement already satisfied: requests>=2.20 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (2.29.0)
Collecting multitasking>=0.0.7 (from yfinance==0.1.67)
  Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Requirement already satisfied: lxml>=4.5.1 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (4.9.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from pandas>=0.24->yfinance==0.1.67) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from pandas>=0.24->yfinance==0.1.67) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (2023.5.7)
Requirement already satisfied: six>=1.5 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=0.24->yfinance==0.1.67) (1.16.0)
Installing collected packages: multitasking, yfinance
Successfully installed multitasking-0.0.11 yfinance-0.1.67

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['bs4==4.10.0']

[+] 0.0s
[+] 0.1s
pkgs/main/linux-64 ━━━━━╸━━━━━━━━━━━━━━━╸━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.1s
pkgs/main/noarch   ━━━╸━━━━━━━━━━━━━━━╸━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.1s
pkgs/r/linux-64    ━━━━━━━━━━━━╸━━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.1s
pkgs/r/noarch      ━━━━━━━━━╸━━━━━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.1s[+] 0.2s
pkgs/main/linux-64 ━━━━━━━╸━━━━━━━━━━━━━━━╸━   0.0 B /  ??.?MB @  ??.?MB/s  0.2s
pkgs/main/noarch   ━━━━╸━━━━━━━━━━━━━━━╸━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.2s
pkgs/r/linux-64    ━━━━━━━━━━━━━╸━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.2s
pkgs/r/noarch      ━━━━━━━━━━╸━━━━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.2s[+] 0.3s
pkgs/main/linux-64 ━━━━━━━━╸━━━━━━━━━━━━━━━━ 282.6kB /  ??.?MB @   1.1MB/s  0.3s
pkgs/main/noarch   ━━━━━╸━━━━━━━━━━━━━━━╸━━━ 417.8kB /  ??.?MB @   1.5MB/s  0.3s
pkgs/r/linux-64    ━━━━━━━━━━━━━━━╸━━━━━━━━━ 372.7kB /  ??.?MB @   1.3MB/s  0.3s
pkgs/r/noarch      ━━━━━━━━━━╸━━━━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.3s[+] 0.4s
pkgs/main/linux-64 ━━━━━━━━━╸━━━━━━━━━━━━━━━ 573.5kB /  ??.?MB @   1.7MB/s  0.4s
pkgs/r/linux-64    ╸━━━━━━━━━━━━━━━╸━━━━━━━━ 536.6kB /  ??.?MB @   1.6MB/s  0.4s
pkgs/r/noarch      ━━━━━━━━━━━━╸━━━━━━━━━━━━ 577.5kB /  ??.?MB @   1.6MB/s  0.4spkgs/main/noarch                                   862.0kB @   2.3MB/s  0.4s
[+] 0.5s
pkgs/main/linux-64 ━━━━━━━━━━━╸━━━━━━━━━━━━━   1.2MB /  ??.?MB @   2.5MB/s  0.5s
pkgs/r/linux-64    ━━╸━━━━━━━━━━━━━━━╸━━━━━━ 925.7kB /  ??.?MB @   1.9MB/s  0.5s
pkgs/r/noarch      ━━━━━━━━━━━━━━━╸━━━━━━━━━   1.0MB /  ??.?MB @   2.1MB/s  0.5s[+] 0.6s
pkgs/main/linux-64 ━━━━━━━━━━━━━━╸━━━━━━━━━━   1.7MB /  ??.?MB @   2.9MB/s  0.6s
pkgs/r/linux-64    ━━━━━╸━━━━━━━━━━━━━━━╸━━━   1.3MB /  ??.?MB @   2.2MB/s  0.6s
pkgs/r/noarch      ━╸━━━━━━━━━━━━━━━╸━━━━━━━   1.4MB /  ??.?MB @   2.3MB/s  0.6s[+] 0.7s
pkgs/main/linux-64 ━━━━━━━━╸━━━━━━━━━━━━━━━━   2.2MB /  ??.?MB @   3.1MB/s  0.7s
pkgs/r/linux-64    ━━━━━━━╸━━━━━━━━━━━━━━━╸━   1.7MB /  ??.?MB @   2.4MB/s  0.7s
pkgs/r/noarch      ━━━╸━━━━━━━━━━━━━━━╸━━━━━   1.7MB /  ??.?MB @   2.4MB/s  0.7s[+] 0.8s
pkgs/main/linux-64 ━━━━━━━━━╸━━━━━━━━━━━━━━━   2.4MB /  ??.?MB @   3.3MB/s  0.8s
pkgs/r/noarch      ━━━╸━━━━━━━━━━━━━━━╸━━━━━   1.7MB /  ??.?MB @   2.4MB/s  0.8spkgs/r/linux-64                                      1.9MB @   2.6MB/s  0.8s
[+] 0.9s
pkgs/main/linux-64 ━━━━━━━━━━━╸━━━━━━━━━━━━━   2.8MB /  ??.?MB @   3.4MB/s  0.9spkgs/r/noarch                                        2.3MB @   2.7MB/s  0.9s
[+] 1.0s
pkgs/main/linux-64 ━━━━━━━━━━━━╸━━━━━━━━━━━━   3.5MB /  ??.?MB @   3.5MB/s  1.0s[+] 1.1s
pkgs/main/linux-64 ━━━━━━━━━━━━━━╸━━━━━━━━━━   3.9MB /  ??.?MB @   3.6MB/s  1.1s[+] 1.2s
pkgs/main/linux-64 ━╸━━━━━━━━━━━━━━━╸━━━━━━━   4.4MB /  ??.?MB @   3.7MB/s  1.2s[+] 1.3s
pkgs/main/linux-64 ━━━╸━━━━━━━━━━━━━━━╸━━━━━   4.9MB /  ??.?MB @   3.8MB/s  1.3s[+] 1.4s
pkgs/main/linux-64 ━━━━╸━━━━━━━━━━━━━━━╸━━━━   5.2MB /  ??.?MB @   3.8MB/s  1.4s[+] 1.5s
pkgs/main/linux-64 ━━━━━━━╸━━━━━━━━━━━━━━━╸━   5.7MB /  ??.?MB @   3.9MB/s  1.5s[+] 1.6s
pkgs/main/linux-64 ━━━━━━━━━╸━━━━━━━━━━━━━━━   6.2MB /  ??.?MB @   4.0MB/s  1.6s[+] 1.7s
pkgs/main/linux-64 ━━━━━━━━━━━╸━━━━━━━━━━━━━   6.6MB /  ??.?MB @   4.0MB/s  1.7s[+] 1.8s
pkgs/main/linux-64 ━━━━━━━━━━━━━━━━━━━━━━━━   6.8MB @   3.9MB/s Finalizing  1.8spkgs/main/linux-64                                 @   3.9MB/s  1.9s

Pinned packages:
  - python 3.7.*


Transaction

  Prefix: /home/jupyterlab/conda/envs/python

  Updating specs:

   - bs4==4.10.0
   - ca-certificates
   - certifi
   - openssl


  Package              Version  Build         Channel                 Size
────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────

  + bs4                 4.10.0  hd3eb1b0_0    pkgs/main/noarch        10kB

  Upgrade:
────────────────────────────────────────────────────────────────────────────

  - ca-certificates   2023.5.7  hbcca054_0    conda-forge
  + ca-certificates  2024.3.11  h06a4308_0    pkgs/main/linux-64     130kB
  - openssl             1.1.1t  h0b41bf4_0    conda-forge
  + openssl             1.1.1w  h7f8727e_0    pkgs/main/linux-64       4MB

  Downgrade:
────────────────────────────────────────────────────────────────────────────

  - beautifulsoup4      4.11.1  pyha770c72_0  conda-forge
  + beautifulsoup4      4.10.0  pyh06a4308_0  pkgs/main/noarch        87kB

  Summary:

  Install: 1 packages
  Upgrade: 2 packages
  Downgrade: 1 packages

  Total download: 4MB

────────────────────────────────────────────────────────────────────────────


[+] 0.0s
Downloading  (1) ━━━━━━━━━━━━━━━━━━━━━━━   0.0 B beautifulsoup4             0.0s
Extracting       ━━━━━━━━━━━━━━━━━━━━━━━       0                            0.0s[+] 0.1s
Downloading  (4) ━━━━━━━━━━━━━━━━━━━━━━━   0.0 B beautifulsoup4             0.1s
Extracting       ━━━━━━━━━━━━━━━━━━━━━━━       0                            0.0sca-certificates                                    130.4kB @ 854.1kB/s  0.2s
beautifulsoup4                                      86.6kB @ 533.8kB/s  0.2s
bs4                                                 10.2kB @  63.0kB/s  0.2s
[+] 0.2s
Downloading  (1) ━╸━━━━━━━━━━━━━━━━━━━━━ 422.7kB openssl                    0.2s
Extracting   (3) ━━━╸━━━━━━━━━━━━━━━╸━━━       0 beautifulsoup4             0.0sopenssl                                              3.9MB @  17.0MB/s  0.2s
[+] 0.3s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━╸━━━━━━━━━━━━━━━╸━━       0 beautifulsoup4             0.1s[+] 0.4s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━╸━━━━━━━━━━━━━━━╸━       0 beautifulsoup4             0.2s[+] 0.5s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━╸━━━━━━━━━━━━━━━━       0 beautifulsoup4             0.3s[+] 0.6s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━━╸━━━━━━━━━━━━━━       0 bs4                        0.4s[+] 0.7s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━━━╸━━━━━━━━━━━━━       0 bs4                        0.5s[+] 0.8s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━━━━╸━━━━━━━━━━━━       0 bs4                        0.6s[+] 0.9s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━━━━━╸━━━━━━━━━━━       0 bs4                        0.7s[+] 1.0s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━━━━━━╸━━━━━━━━━━       0 ca-certificates            0.8s[+] 1.1s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━╸━━━━━━━━━━━━━━━       0 ca-certificates            0.9s[+] 1.2s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━━╸━━━━━━━━━━━━━━       0 ca-certificates            1.0s[+] 1.3s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━━━╸━━━━━━━━━━━━━       0 ca-certificates            1.1s[+] 1.4s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━━━━╸━━━━━━━━━━━━       0 openssl                    1.2s[+] 1.5s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━━━━━╸━━━━━━━━━━━       0 openssl                    1.3s[+] 1.6s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━━━━━━━╸━━━━━━━━━       0 openssl                    1.4s[+] 1.7s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━━━━━━━━╸━━━━━━━━       0 openssl                    1.5s[+] 1.8s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (3) ━━━━╸━━━━━━━━━━━━━━━━━━       1 beautifulsoup4             1.6s[+] 1.9s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (2) ━━━━━━━━━━╸━━━━━━━━━━━━       2 bs4                        1.7s[+] 2.0s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (1) ━━━━━━━━━━━━━━━━╸━━━━━━       3 openssl                    1.8s
Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting nbformat==4.2.0
  Downloading nbformat-4.2.0-py2.py3-none-any.whl (153 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.3/153.3 kB 21.6 MB/s eta 0:00:00
Requirement already satisfied: ipython-genutils in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from nbformat==4.2.0) (0.2.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from nbformat==4.2.0) (4.17.3)
Requirement already satisfied: jupyter-core in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from nbformat==4.2.0) (4.12.0)
Requirement already satisfied: traitlets>=4.1 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from nbformat==4.2.0) (5.9.0)
Requirement already satisfied: attrs>=17.4.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (23.1.0)
Requirement already satisfied: importlib-metadata in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (4.11.4)
Requirement already satisfied: importlib-resources>=1.4.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (5.12.0)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (1.3.10)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (0.19.3)
Requirement already satisfied: typing-extensions in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (4.5.0)
Requirement already satisfied: zipp>=3.1.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from importlib-resources>=1.4.0->jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (3.15.0)
Installing collected packages: nbformat
  Attempting uninstall: nbformat
    Found existing installation: nbformat 5.8.0
    Uninstalling nbformat-5.8.0:
      Successfully uninstalled nbformat-5.8.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyter-server 1.24.0 requires nbformat>=5.2.0, but you have nbformat 4.2.0 which is incompatible.
nbclient 0.7.4 requires nbformat>=5.1, but you have nbformat 4.2.0 which is incompatible.
nbconvert 7.4.0 requires nbformat>=5.1, but you have nbformat 4.2.0 which is incompatible.
Successfully installed nbformat-4.2.0

In [2]:
import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In Python, you can ignore warnings using the warnings module. You can use the filterwarnings function to filter or ignore specific warning messages or categories.

In [172]:
import warnings
# Ignore all warnings
warnings.filterwarnings("ignore", category=FutureWarning)

## Define Graphing Function

In this section, we define the function `make_graph`. You don't have to know how the function works, you should only care about the inputs. It takes a dataframe with stock data (dataframe must contain Date and Close columns), a dataframe with revenue data (dataframe must contain Date and Revenue columns), and the name of the stock.

In [173]:
def make_graph(stock_data, revenue_data, stock):
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, subplot_titles=("Historical Share Price", "Historical Revenue"), vertical_spacing = .3)
    stock_data_specific = stock_data[stock_data.Date <= '2021--06-14']
    revenue_data_specific = revenue_data[revenue_data.Date <= '2021-04-30']
    fig.add_trace(go.Scatter(x=pd.to_datetime(stock_data_specific.Date, infer_datetime_format=True), y=stock_data_specific.Close.astype("float"), name="Share Price"), row=1, col=1)
    fig.add_trace(go.Scatter(x=pd.to_datetime(revenue_data_specific.Date, infer_datetime_format=True), y=revenue_data_specific.Revenue.astype("float"), name="Revenue"), row=2, col=1)
    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)
    fig.update_yaxes(title_text="Price ($US)", row=1, col=1)
    fig.update_yaxes(title_text="Revenue ($US Millions)", row=2, col=1)
    fig.update_layout(showlegend=False,
    height=900,
    title=stock,
    xaxis_rangeslider_visible=True)
    fig.show()

## Question 1: Use yfinance to Extract Stock Data

Using the `Ticker` function enter the ticker symbol of the stock we want to extract data on to create a ticker object. The stock is Tesla and its ticker symbol is `TSLA`.

In [174]:
tsla = yf.Ticker('TSLA')

Using the ticker object and the function `history` extract stock information and save it in a dataframe named `tesla_data`. Set the `period` parameter to `max` so we get information for the maximum amount of time.

In [175]:
#tesla_data = tsla.history(period = "min")
tesla_data = tsla.history()
tesla_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-03-12,177.770004,179.429993,172.410004,177.539993,87391700,0,0
2024-03-13,173.050003,176.050003,169.149994,169.479996,106524500,0,0
2024-03-14,167.770004,171.169998,160.509995,162.500000,126325700,0,0
2024-03-15,163.160004,165.179993,160.759995,163.570007,96971900,0,0
2024-03-18,170.020004,174.720001,165.899994,173.800003,108214400,0,0
2024-03-19,172.360001,172.820007,167.419998,171.320007,77271400,0,0
2024-03-20,173.000000,176.250000,170.820007,175.660004,83846700,0,0
2024-03-21,176.389999,178.179993,171.800003,172.820007,73178000,0,0
2024-03-22,166.690002,171.199997,166.300003,170.830002,75454700,0,0
2024-03-25,168.759995,175.240005,168.729996,172.630005,74228600,0,0
2024-03-26,178.580002,184.250000,177.380005,177.669998,113186200,0,0
2024-03-27,181.410004,181.910004,176.000000,179.830002,81804000,0,0
2024-03-28,177.449997,179.570007,175.300003,175.789993,77654800,0,0
2024-04-01,176.169998,176.750000,170.210007,175.220001,81562100,0,0
2024-04-02,164.750000,167.690002,163.429993,166.630005,116650600,0,0
2024-04-03,164.020004,168.820007,163.279999,168.380005,82950100,0,0
2024-04-04,170.070007,177.190002,168.009995,171.110001,123162000,0,0
2024-04-05,169.080002,170.860001,160.509995,164.899994,141250700,0,0
2024-04-08,169.339996,174.500000,167.789993,172.979996,104423300,0,0
2024-04-09,172.910004,179.220001,171.919998,176.880005,103232700,0,0
2024-04-10,173.039993,174.929993,170.009995,171.759995,84532400,0,0
2024-04-11,172.550003,175.880005,168.509995,174.600006,94367800,0,0
2024-04-12,172.320007,173.809906,171.707108,172.675995,18037777,0,0

**Reset the index** using the `reset_index(inplace=True)` function on the tesla_data DataFrame and display the first five rows of the `tesla_data` dataframe using the `head` function. Take a screenshot of the results and code from the beginning of Question 1 to the results below.

In [176]:
tesla_data.reset_index(inplace=True)

In [177]:
close = tesla_data['Close'].head(5)
close

0    177.539993
1    169.479996
2    162.500000
3    163.570007
4    173.800003
Name: Close, dtype: float64

## Question 2: Use Webscraping to Extract Tesla Revenue Data

Use the `requests` library to download the webpage https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm Save the text of the response as a variable named `html_data`.

In [178]:
!pip install yfinance==0.1.67
!mamba install bs4==4.10.0 -y
!pip install nbformat==4.2.0
import yfinance as yf
import pandas as pd
import requests
! mamba install bs4 == 4.6.10
from bs4 import BeautifulSoup
import plotly.graph_objects as go
from plotly.subplots import make_subplots
! mamba install html5lib == 1.1 -y
! pip install lxml == 4.6.4
import warnings
! pip install html5lib
! pip show html5lib
! pip install lxml
! pip install beautifulsoup4
from bs4 import BeautifulSoup


url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm'
html_data = requests.get(url).text
#print(html_data)

Requirement already satisfied: yfinance==0.1.67 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (0.1.67)
Requirement already satisfied: pandas>=0.24 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (1.3.5)
Requirement already satisfied: numpy>=1.15 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (1.21.6)
Requirement already satisfied: requests>=2.20 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (2.29.0)
Requirement already satisfied: multitasking>=0.0.7 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (0.0.11)
Requirement already satisfied: lxml>=4.5.1 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance==0.1.67) (4.9.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from pandas>=0.24->yfinance==0.1.67) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from pandas>=0.24->yfinance==0.1.67) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (2023.5.7)
Requirement already satisfied: six>=1.5 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=0.24->yfinance==0.1.67) (1.16.0)

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['bs4==4.10.0']

[+] 0.0s
pkgs/main/linux-64 ━━━╸━━━━━━━━━━━━━━━╸━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.0s[+] 0.1s
pkgs/main/linux-64 ━━━╸━━━━━━━━━━━━━━━╸━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.1s
pkgs/main/noarch   ━━━━━━━━━━━━━╸━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.1s
pkgs/r/linux-64    ━━━━━━━━━━━╸━━━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.1s
pkgs/r/noarch      ╸━━━━━━━━━━━━━━━╸━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.1spkgs/main/linux-64                                            No change
pkgs/r/noarch                                                 No change
pkgs/r/linux-64                                               No change
pkgs/main/noarch                                              No change

Pinned packages:
  - python 3.7.*


Transaction

  Prefix: /home/jupyterlab/conda/envs/python

  All requested packages already installed

Requirement already satisfied: nbformat==4.2.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (4.2.0)
Requirement already satisfied: ipython-genutils in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from nbformat==4.2.0) (0.2.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from nbformat==4.2.0) (4.17.3)
Requirement already satisfied: jupyter-core in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from nbformat==4.2.0) (4.12.0)
Requirement already satisfied: traitlets>=4.1 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from nbformat==4.2.0) (5.9.0)
Requirement already satisfied: attrs>=17.4.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (23.1.0)
Requirement already satisfied: importlib-metadata in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (4.11.4)
Requirement already satisfied: importlib-resources>=1.4.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (5.12.0)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (1.3.10)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (0.19.3)
Requirement already satisfied: typing-extensions in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (4.5.0)
Requirement already satisfied: zipp>=3.1.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from importlib-resources>=1.4.0->jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (3.15.0)

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

invalid package specification: ==

CondaValueError: invalid package specification: ==


                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

invalid package specification: ==

CondaValueError: invalid package specification: ==

ERROR: Invalid requirement: '=='
Requirement already satisfied: html5lib in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (1.1)
Requirement already satisfied: six>=1.9 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from html5lib) (1.16.0)
Requirement already satisfied: webencodings in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from html5lib) (0.5.1)
Name: html5lib
Version: 1.1
Summary: HTML parser based on the WHATWG HTML specification
Home-page: https://github.com/html5lib/html5lib-python
Author:
Author-email:
License: MIT License
Location: /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages
Requires: six, webencodings
Required-by:
Requirement already satisfied: lxml in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (4.9.2)
Requirement already satisfied: beautifulsoup4 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (4.10.0)
Requirement already satisfied: soupsieve>1.2 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from beautifulsoup4) (2.3.2.post1)

Parse the html data using `beautiful_soup`.

In [179]:
soup = BeautifulSoup(html_data, 'lxml')  

soup.find_all('tbody')[1]

<tbody>
<tr>
<td style="text-align:center">2022-09-30</td>
<td style="text-align:center">$21,454</td>
</tr>
<tr>
<td style="text-align:center">2022-06-30</td>
<td style="text-align:center">$16,934</td>
</tr>
<tr>
<td style="text-align:center">2022-03-31</td>
<td style="text-align:center">$18,756</td>
</tr>
<tr>
<td style="text-align:center">2021-12-31</td>
<td style="text-align:center">$17,719</td>
</tr>
<tr>
<td style="text-align:center">2021-09-30</td>
<td style="text-align:center">$13,757</td>
</tr>
<tr>
<td style="text-align:center">2021-06-30</td>
<td style="text-align:center">$11,958</td>
</tr>
<tr>
<td style="text-align:center">2021-03-31</td>
<td style="text-align:center">$10,389</td>
</tr>
<tr>
<td style="text-align:center">2020-12-31</td>
<td style="text-align:center">$10,744</td>
</tr>
<tr>
<td style="text-align:center">2020-09-30</td>
<td style="text-align:center">$8,771</td>
</tr>
<tr>
<td style="text-align:center">2020-06-30</td>
<td style="text-align:center">$6,036</td>
</tr>
<tr>
<td style="text-align:center">2020-03-31</td>
<td style="text-align:center">$5,985</td>
</tr>
<tr>
<td style="text-align:center">2019-12-31</td>
<td style="text-align:center">$7,384</td>
</tr>
<tr>
<td style="text-align:center">2019-09-30</td>
<td style="text-align:center">$6,303</td>
</tr>
<tr>
<td style="text-align:center">2019-06-30</td>
<td style="text-align:center">$6,350</td>
</tr>
<tr>
<td style="text-align:center">2019-03-31</td>
<td style="text-align:center">$4,541</td>
</tr>
<tr>
<td style="text-align:center">2018-12-31</td>
<td style="text-align:center">$7,226</td>
</tr>
<tr>
<td style="text-align:center">2018-09-30</td>
<td style="text-align:center">$6,824</td>
</tr>
<tr>
<td style="text-align:center">2018-06-30</td>
<td style="text-align:center">$4,002</td>
</tr>
<tr>
<td style="text-align:center">2018-03-31</td>
<td style="text-align:center">$3,409</td>
</tr>
<tr>
<td style="text-align:center">2017-12-31</td>
<td style="text-align:center">$3,288</td>
</tr>
<tr>
<td style="text-align:center">2017-09-30</td>
<td style="text-align:center">$2,985</td>
</tr>
<tr>
<td style="text-align:center">2017-06-30</td>
<td style="text-align:center">$2,790</td>
</tr>
<tr>
<td style="text-align:center">2017-03-31</td>
<td style="text-align:center">$2,696</td>
</tr>
<tr>
<td style="text-align:center">2016-12-31</td>
<td style="text-align:center">$2,285</td>
</tr>
<tr>
<td style="text-align:center">2016-09-30</td>
<td style="text-align:center">$2,298</td>
</tr>
<tr>
<td style="text-align:center">2016-06-30</td>
<td style="text-align:center">$1,270</td>
</tr>
<tr>
<td style="text-align:center">2016-03-31</td>
<td style="text-align:center">$1,147</td>
</tr>
<tr>
<td style="text-align:center">2015-12-31</td>
<td style="text-align:center">$1,214</td>
</tr>
<tr>
<td style="text-align:center">2015-09-30</td>
<td style="text-align:center">$937</td>
</tr>
<tr>
<td style="text-align:center">2015-06-30</td>
<td style="text-align:center">$955</td>
</tr>
<tr>
<td style="text-align:center">2015-03-31</td>
<td style="text-align:center">$940</td>
</tr>
<tr>
<td style="text-align:center">2014-12-31</td>
<td style="text-align:center">$957</td>
</tr>
<tr>
<td style="text-align:center">2014-09-30</td>
<td style="text-align:center">$852</td>
</tr>
<tr>
<td style="text-align:center">2014-06-30</td>
<td style="text-align:center">$769</td>
</tr>
<tr>
<td style="text-align:center">2014-03-31</td>
<td style="text-align:center">$621</td>
</tr>
<tr>
<td style="text-align:center">2013-12-31</td>
<td style="text-align:center">$615</td>
</tr>
<tr>
<td style="text-align:center">2013-09-30</td>
<td style="text-align:center">$431</td>
</tr>
<tr>
<td style="text-align:center">2013-06-30</td>
<td style="text-align:center">$405</td>
</tr>
<tr>
<td style="text-align:center">2013-03-31</td>
<td style="text-align:center">$562</td>
</tr>
<tr>
<td style="text-align:center">2012-12-31</td>
<td style="text-align:center">$306</td>
</tr>
<tr>
<td style="text-align:center">2012-09-30</td>
<td style="text-align:center">$50</td>
</tr>
<tr>
<td style="text-align:center">2012-06-30</td>
<td style="text-align:center">$27</td>
</tr>
<tr>
<td style="text-align:center">2012-03-31</td>
<td style="text-align:center">$30</td>
</tr>
<tr>
<td style="text-align:center">2011-12-31</td>
<td style="text-align:center">$39</td>
</tr>
<tr>
<td style="text-align:center">2011-09-30</td>
<td style="text-align:center">$58</td>
</tr>
<tr>
<td style="text-align:center">2011-06-30</td>
<td style="text-align:center">$58</td>
</tr>
<tr>
<td style="text-align:center">2011-03-31</td>
<td style="text-align:center">$49</td>
</tr>
<tr>
<td style="text-align:center">2010-12-31</td>
<td style="text-align:center">$36</td>
</tr>
<tr>
<td style="text-align:center">2010-09-30</td>
<td style="text-align:center">$31</td>
</tr>
<tr>
<td style="text-align:center">2010-06-30</td>
<td style="text-align:center">$28</td>
</tr>
<tr>
<td style="text-align:center">2010-03-31</td>
<td style="text-align:center">$21</td>
</tr>
<tr>
<td style="text-align:center">2009-12-31</td>
<td style="text-align:center"></td>
</tr>
<tr>
<td style="text-align:center">2009-09-30</td>
<td style="text-align:center">$46</td>
</tr>
<tr>
<td style="text-align:center">2009-06-30</td>
<td style="text-align:center">$27</td>
</tr>
</tbody>

Using `BeautifulSoup` or the `read_html` function extract the table with 
and store it into a dataframe named `tesla_revenue`. The dataframe should have columns `Date` and `Revenue`.

<details><summary>Click here if you need help locating the table</summary>

```
    
Below is the code to isolate the table, you will now need to loop through the rows and columns like in the previous lab
    
soup.find_all("tbody")[1]
    
If you want to use the read_html function the table is located at index 1

We are focusing on quarterly revenue in the lab.
```

</details>

In [180]:
#tesla_revenue = pd.DataFrame(columns = ['Date','Revenue'])

#for row in soup.find_all("tbody":
   # col = row.find_all('td')
   # Date = col[0].text
   # Revenue = col[1].text
    
#tesla_revenue

read_html_pandas_data = pd.read_html(str(soup))
tesla_revenue = read_html_pandas_data[1]

tesla_revenue.rename(columns={
    'Tesla Quarterly Revenue(Millions of US $)': 'Date',
    'Tesla Quarterly Revenue(Millions of US $).1': 'Revenue'
}, inplace=True)




#for row in soup.find('tbody').find_all('tr'):

Execute the following line to remove the comma and dollar sign from the `Revenue` column.

In [182]:
#print(tesla_revenue)
tesla_revenue["Revenue"] = tesla_revenue['Revenue'].str.replace(',|\$',"")
tesla_revenue['Date'] = pd.to_datetime(tesla_revenue['Date'])
tesla_revenue['Date'].head(5)

0   2022-09-30
1   2022-06-30
2   2022-03-31
3   2021-12-31
4   2021-09-30
Name: Date, dtype: datetime64[ns]

Execute the following lines to remove an null or empty strings in the Revenue column.

In [184]:
tesla_revenue.dropna(inplace=True)

tesla_revenue = tesla_revenue[tesla_revenue['Revenue'] != ""]

Display the last 5 row of the `tesla_revenue` dataframe using the `tail` function. Take a screenshot of the results.

In [185]:
tesla_revenue.tail(5)

         Date Revenue
48 2010-09-30      31
49 2010-06-30      28
50 2010-03-31      21
52 2009-09-30      46
53 2009-06-30      27

## Question 3: Use yfinance to Extract Stock Data

Using the `Ticker` function enter the ticker symbol of the stock we want to extract data on to create a ticker object. The stock is GameStop and its ticker symbol is `GME`.

In [186]:
import yfinance as yf
gme = yf.Ticker("GME")

Using the ticker object and the function `history` extract stock information and save it in a dataframe named `gme_data`. Set the `period` parameter to `max` so we get information for the maximum amount of time.

In [187]:
gme_data = gme.history(period='max')

**Reset the index** using the `reset_index(inplace=True)` function on the gme_data DataFrame and display the first five rows of the `gme_data` dataframe using the `head` function. Take a screenshot of the results and code from the beginning of Question 3 to the results below.

In [188]:
gme_data.reset_index(inplace=True)
gme_data.tail(5)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
5574,2024-04-08,11.30,11.37,10.83,10.8300,3659100,0.0,0.0
5575,2024-04-09,10.85,11.18,10.73,11.0100,3514400,0.0,0.0
5576,2024-04-10,10.90,11.07,10.75,10.8500,3546200,0.0,0.0
5577,2024-04-11,10.91,11.39,10.80,11.2900,3796600,0.0,0.0
5578,2024-04-12,11.21,11.23,10.97,11.0925,488179,0.0,0.0

## Question 4: Use Webscraping to Extract GME Revenue Data

Use the `requests` library to download the webpage https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.html. Save the text of the response as a variable named `html_data`.

In [189]:
url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.html'

page = requests.get(url)

Parse the html data using `beautiful_soup`.

In [190]:
soup = BeautifulSoup(page.content, 'html.parser')

Using `BeautifulSoup` or the `read_html` function extract the table with `GameStop Revenue` and store it into a dataframe named `gme_revenue`. The dataframe should have columns `Date` and `Revenue`. Make sure the comma and dollar sign is removed from the `Revenue` column using a method similar to what you did in Question 2.

<details><summary>Click here if you need help locating the table</summary>

```
    
Below is the code to isolate the table, you will now need to loop through the rows and columns like in the previous lab
    
soup.find_all("tbody")[1]
    
If you want to use the read_html function the table is located at index 1


```

</details>

In [191]:
tables = pd.read_html(url)
gme_revenue = tables[1]

gme_revenue.rename(columns={
    'GameStop Quarterly Revenue(Millions of US $)': 'Date',
    'GameStop Quarterly Revenue(Millions of US $).1': 'Revenue'
}, inplace=True)

#gme_revenue
gme_revenue.to_csv('gme_revenue.csv', index=False)
gme_revenue
#file = pd.to_csv(gme_revenue)
#file

          Date Revenue
0   2020-04-30  $1,021
1   2020-01-31  $2,194
2   2019-10-31  $1,439
3   2019-07-31  $1,286
4   2019-04-30  $1,548
..         ...     ...
57  2006-01-31  $1,667
58  2005-10-31    $534
59  2005-07-31    $416
60  2005-04-30    $475
61  2005-01-31    $709

[62 rows x 2 columns]

Display the last five rows of the `gme_revenue` dataframe using the `tail` function. Take a screenshot of the results.

In [192]:
gme_revenue.tail(5)

          Date Revenue
57  2006-01-31  $1,667
58  2005-10-31    $534
59  2005-07-31    $416
60  2005-04-30    $475
61  2005-01-31    $709

## Question 5: Plot Tesla Stock Graph

Use the `make_graph` function to graph the Tesla Stock Data, also provide a title for the graph. The structure to call the `make_graph` function is `make_graph(tesla_data, tesla_revenue, 'Tesla')`. Note the graph will only show data upto June 2021.

In [ ]:
tesla_revenue.head(3)

In [193]:
tesla_revenue['Date'].head(5)

0   2022-09-30
1   2022-06-30
2   2022-03-31
3   2021-12-31
4   2021-09-30
Name: Date, dtype: datetime64[ns]

In [200]:
def make_graph(tesla_data, tesla_revenue, 'Tesla'):
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, subplot_titles=("Historical Share Price", "Historical Revenue"), vertical_spacing = .3)
    stock_data_specific = tesla_data[Date.Date <= '2021--06-14']
    revenue_data_specific = tesla_revenue[Revenue.Date <= '2021-06-14']
    fig.add_trace(go.Scatter(x=pd.to_datetime(stock_data_specific.Date, infer_datetime_format=True), y=stock_data_specific.Close.astype("float"), name="Share Price"), row=1, col=1)
    fig.add_trace(go.Scatter(x=pd.to_datetime(revenue_data_specific.Date, infer_datetime_format=True), y=revenue_data_specific.Revenue.astype("float"), name="Revenue"), row=2, col=1)
    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)
    fig.update_yaxes(title_text="Price ($US)", row=1, col=1)
    fig.update_yaxes(title_text="Revenue ($US Millions)", row=2, col=1)
    fig.update_layout(showlegend=False,
    height=900,
    title=stock,
    xaxis_rangeslider_visible=True)
    fig.show()

## Question 6: Plot GameStop Stock Graph

Use the `make_graph` function to graph the GameStop Stock Data, also provide a title for the graph. The structure to call the `make_graph` function is `make_graph(gme_data, gme_revenue, 'GameStop')`. Note the graph will only show data upto June 2021.

In [ ]:
def make_graph(gme_data, gme_revenue, 'Gamestop'):
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, subplot_titles=("Historical Share Price", "Historical Revenue"), vertical_spacing = .3)
    stock_data_specific = gme_data[Date.Date <= '2021--06-14']
    revenue_data_specific = gme_revenue[Revenue.Date <= '2021-06-14']
    fig.add_trace(go.Scatter(x=pd.to_datetime(stock_data_specific.Date, infer_datetime_format=True), y=stock_data_specific.Close.astype("float"), name="Share Price"), row=1, col=1)
    fig.add_trace(go.Scatter(x=pd.to_datetime(revenue_data_specific.Date, infer_datetime_format=True), y=revenue_data_specific.Revenue.astype("float"), name="Revenue"), row=2, col=1)
    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)
    fig.update_yaxes(title_text="Price ($US)", row=1, col=1)
    fig.update_yaxes(title_text="Revenue ($US Millions)", row=2, col=1)
    fig.update_layout(showlegend=False,
    height=900,
    title=stock,
    xaxis_rangeslider_visible=True)
    fig.show()

<h2>About the Authors:</h2> 

<a href="https://www.linkedin.com/in/joseph-s-50398b136/">Joseph Santarcangelo</a> has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.

Azim Hirjani

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By    | Change Description        |
| ----------------- | ------- | ------------- | ------------------------- |
| 2022-02-28        | 1.2     | Lakshmi Holla | Changed the URL of GameStop |
| 2020-11-10        | 1.1     | Malika Singla | Deleted the Optional part |
| 2020-08-27        | 1.0     | Malika Singla | Added lab to GitLab       |

<hr>

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>

<p>